apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-clock-app
  labels:
    app: python-clock-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-clock-app
  template:
    metadata:
      labels:
        app: python-clock-app
    spec:
      containers:
      - name: clock-app
        image: docker.io/eli0504167101/python-clock-app:36
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-clock-service
spec:
  selector:
    app: python-clock-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
