pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "docker.io/eli0504167101/python-clock-app"
    }

    stages {
        stage('Cloning Code') {
            steps {
                checkout scm
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running python linter or tests...'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    dir('jenkins-app1') {
                        sh "docker build -t ${DOCKER_IMAGE}:${env.BUILD_NUMBER} ."
                    }
                }
            }
        }

        stage('Update ArgoCD Manifests') {
            steps {
                dir('k8s-manifests-repo') {
                    // משיכת התיקייה
                    git url: 'https://github.com/eli0504167101/devops_course.git',
                        credentialsId: 'github-creds',
                        branch: 'master'
                    
                    // עדכון הטאג של האימג' בתוך קובץ ה-yaml החדש שיצרת
                    sh "sed -i 's|image: .*python-clock-app:.*|image: ${DOCKER_IMAGE}:${env.BUILD_NUMBER}|g' jenkins-app1/deployment.yaml"
                    
                    // הגדרות גיט ודחיפה חזרה
                    sh "git config user.email 'jenkins@local.com'"
                    sh "git config user.name 'Jenkins CI'"
                    sh "git add jenkins-app1/deployment.yaml"
                    sh "git commit -m 'Automated deployment: updated image tag to build ${env.BUILD_NUMBER} [skip ci]'"
                    
                    withCredentials([usernamePassword(credentialsId: 'github-creds', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        // ה-sh מתחיל נקי, והגרש הבודד עוטף אך ורק את הפקודה עצמה
                        sh 'git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/eli0504167101/devops_course.git master'
                    }
                }
            }
        }
    }
}
