pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "docker.io/eli0504167101/python-clock-app"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('Run Tests') {
            steps {
                echo "Running python linter or tests..."
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    dir('jenkins-app1') {
                        sh "docker build -t ${DOCKER_IMAGE}:${env.BUILD_NUMBER} ."
                    }
                }
            }
        }

        stage('Update ArgoCD Manifests') {
            steps {
                dir('k8s-manifests-repo') {
                    script {
                        sh "sed -i 's|image: .*python-clock-app:.*|image: ${DOCKER_IMAGE}:${env.BUILD_NUMBER}|g' jenkins-app1/deployment.yaml"
                        sh '''
                        git config user.email "jenkins@local.com"
                        git config user.name "Jenkins CI"
                        git add jenkins-app1/deployment.yaml
                        git commit -m "Automated deployment: updated image tag to build ${BUILD_NUMBER} [skip ci]"
                        '''
                     withCredentials([usernamePassword(credentialsId: 'github-creds', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
    sh '''
    # 1. הגדרת ה-credential helper
    git config --local credential.helper store
    echo "https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com" > ~/.git-credentials
    
    # 2. משיכה של השינויים החדשים מה-Remote ושילובם (Rebase)
    git pull origin master --rebase
    
    # 3. דחיפה של השינויים שלנו (כולל הקומיט של ה-deployment)
    git push origin HEAD:master
    
    # 4. ניקוי
    rm ~/.git-credentials
    git config --local --unset credential.helper
    '''
}
                    }
                }
            }
        }
    }
}
