apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: eli0504167101/app-node:latest # <--- תשנה בדיוק לשורה הזו
    ports:
    - containerPort: 80
