services:
  master:
    build: ./app
    image: ubuntu:22.04  # <--- שנה לזה
    container_name: master-node
    tty: true
    networks:
      - ansible-net
    volumes:
      - .:/ansible
    working_dir: /ansible

    command: >
      bash -c "apt update && apt install -y openssh-client python3 && tail -f /dev/null"

  slave:
    build: ./app
    image: ubuntu:22.04  # <--- שנה לזה
    container_name: slave-node
    networks:
      - ansible-net
    expose:
      - 5015
    ports:
      - "5015:5015"
    command: >
      bash -c "apt update && apt install -y openssh-server python3 && 
      mkdir /var/run/sshd && 
      echo 'root:root' | chpasswd && 
      sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && 
      /usr/sbin/sshd -D"
networks:
  ansible-net:
    driver: bridge