name: CI Deploy02 to Docker Hub

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        cd k8s/deploy02
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/deploy02:v1 .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/deploy02:v1
